//
//  EndpointFileGenerator.swift
//  MIOServerKit
//
//  Renders the scanned @Endpoint annotations into a Swift registration file
//  (and optionally a JSON description of the routes).
//

import Foundation

public struct EndpointFileGenerator
{
    public enum GeneratorError: Error, CustomStringConvertible
    {
        case duplicateRoute( method: String, path: String, handlers: [ScannedEndpoint] )

        public var description: String {
            switch self {
            case .duplicateRoute( let method, let path, let handlers ):
                let locations = handlers.map { "\($0.handler) (\($0.file):\($0.line))" }.joined( separator: ", " )
                return "Duplicate route \(method.uppercased()) \(path) registered by: \(locations)"
            }
        }
    }

    let endpoints: [ScannedEndpoint]

    public init( endpoints: [ScannedEndpoint] ) {
        self.endpoints = endpoints
    }

    /// Fails when two handlers claim the same method + path.
    public func validate() throws
    {
        var routes: [String: [ScannedEndpoint]] = [:]
        for endpoint in endpoints {
            for method in endpoint.methods {
                routes[ "\(method) \(endpoint.path)", default: [] ].append( endpoint )
            }
        }
        for (route, handlers) in routes.sorted( by: { $0.key < $1.key } ) where handlers.count > 1 {
            let parts = route.split( separator: " ", maxSplits: 1 )
            throw GeneratorError.duplicateRoute( method: String( parts[0] ), path: String( parts[1] ), handlers: handlers )
        }
    }

    /// Generates the Swift file that registers every endpoint into a Router.
    public func generateSwift( extraImports: [String] = [] ) throws -> String
    {
        try validate()

        var lines: [String] = []
        lines.append( "//" )
        lines.append( "//  Endpoints+Generated.swift" )
        lines.append( "//" )
        lines.append( "//  Generated by generate-endpoints — DO NOT EDIT." )
        lines.append( "//  Routes are declared with @Endpoint annotations in the source files." )
        lines.append( "//" )
        lines.append( "" )
        lines.append( "import MIOServerKit" )
        for module in extraImports.sorted() where module != "MIOServerKit" {
            lines.append( "import \(module)" )
        }
        lines.append( "" )
        lines.append( "public extension Router" )
        lines.append( "{" )
        lines.append( "    /// Registers every function annotated with @Endpoint into this router." )
        lines.append( "    @discardableResult" )
        lines.append( "    func registerGeneratedEndpoints() -> Router" )
        lines.append( "    {" )

        // Group by path: Router.endpoint(path) creates a fresh Endpoint node
        // each call, so all methods of a path must chain on a single call.
        let byPath = Dictionary( grouping: endpoints, by: { $0.path } )

        var first = true
        for path in byPath.keys.sorted() {
            if first == false { lines.append( "" ) }
            first = false

            lines.append( "        endpoint( \(quoted( path )) )" )
            for endpoint in byPath[ path ]!.sorted( by: { $0.handler < $1.handler } ) {
                for method in endpoint.methods {
                    lines.append( "            .\(method)( \(endpoint.handler) )" )
                }
            }
        }

        if endpoints.isEmpty == false { lines.append( "" ) }
        lines.append( "        return self" )
        lines.append( "    }" )
        lines.append( "}" )
        lines.append( "" )

        return lines.joined( separator: "\n" )
    }

    /// Generates a JSON description of the routes (configuration file).
    public func generateJSON() throws -> String
    {
        try validate()

        let encoder = JSONEncoder()
        encoder.outputFormatting = [ .prettyPrinted, .sortedKeys ]
        let sorted = endpoints.sorted { ( $0.path, $0.handler ) < ( $1.path, $1.handler ) }
        let data = try encoder.encode( [ "endpoints": sorted ] )
        return String( decoding: data, as: UTF8.self ) + "\n"
    }

    func quoted( _ string: String ) -> String {
        let escaped = string
            .replacingOccurrences( of: "\\", with: "\\\\" )
            .replacingOccurrences( of: "\"", with: "\\\"" )
        return "\"\(escaped)\""
    }
}
